#ifndef SIGNALS_HPP
#define SIGNALS_HPP

enum class Signals {
    BUTTON_COMMAND_1,
    BUTTON_COMMAND_2,
    BUTTON_COMMAND_3,
    BUTTON_COMMAND_4,
    BUTTON_UP_1,
    BUTTON_UP_2,
    BUTTON_UP_3,
    BUTTON_DOWN_2,
    BUTTON_DOWN_3,
    BUTTON_DOWN_4,
    STOP_BUTTON,
    OBSTRUCTION,
    FLOOR_SENSOR,
    DOOR_LAMP,
    LIGHT_STOP,
    LIGHT_COMMAND_1,
    LIGHT_COMMAND_2,
    LIGHT_COMMAND_3,
    LIGHT_COMMAND_4,
    LIGHT_UP_1,
    LIGHT_UP_2,
    LIGHT_UP_3,
    LIGHT_DOWN_2,
    LIGHT_DOWN_3,
    LIGHT_DOWN_4,
    LIGHT_FLOOR_1,
    LIGHT_FLOOR_2,
    LIGHT_FLOOR_3,
    LIGHT_FLOOR_4,
    MOTOR_DIR,
    MOTOR_SPEED,
    NUM_SIGNALS
};

#endif //SIGNALS_HPP
